CREATE TABLE `its_kdn_user` (
  `DEP_ID` VARCHAR(10) NOT NULL COMMENT '부서ID',
  `LOGIN_ID` VARCHAR(6) NOT NULL COMMENT '로그인ID',
  `USER_ID` VARCHAR(5) COMMENT '사용자ID',
  `USER_NM` VARCHAR(10) COMMENT '이름',
  `USER_PWD` VARCHAR(100) COMMENT '비번',
  `EMAIL` VARCHAR(30) COMMENT '이메일',
  `CELL_PHONE` VARCHAR(15) COMMENT '전화번호',
  `PWD_FAIL_COUNT` DECIMAL(10,0) COMMENT '로그인실패카운트',
  `DEL_YN` VARCHAR(1) COMMENT '삭제여부',
  `POSITION_CODE` VARCHAR(4) COMMENT '직책코드',
  `POSITION_NM` VARCHAR(12) COMMENT '직책',
  `CP_AUTH_YN` VARCHAR(1) COMMENT '형상연계여부',
  `CP_AUTH_DT` VARCHAR(14) COMMENT '형상연계일',
  PRIMARY KEY (`DEP_ID`, `LOGIN_ID`)
);

CREATE TABLE `its_kdn_dep` (
  `DEP_ID` VARCHAR(10) PRIMARY KEY NOT NULL COMMENT '부서코드',
  `PAR_DEP_ID` VARCHAR(10) COMMENT '대분류',
  `DEP_TITLE` VARCHAR(20) COMMENT '부서명',
  `KEPCO_MAP` VARCHAR(10) COMMENT '본사여부'
);

CREATE TABLE `smeta_user` (
  `DEP_ID` VARCHAR(10) NOT NULL COMMENT '부서코드',
  `SABUN` VARCHAR(10) NOT NULL COMMENT '사번',
  `LOGIN_ID` VARCHAR(6) NOT NULL COMMENT '로그인ID',
  `DEPT_CD` VARCHAR(10) COMMENT '부서코드',
  PRIMARY KEY (`DEP_ID`, `SABUN`, `LOGIN_ID`)
);

CREATE TABLE `its_kepco_login` (
  `SABUN` VARCHAR(10) PRIMARY KEY NOT NULL,
  `PASS` VARCHAR(500) NOT NULL,
  `PWD_FAIL_COUNT` INT,
  `LOCK_YN` CHAR(1) DEFAULT 'N'
);

CREATE TABLE `its_kdn_dep_map` (
  `DEP_ID` VARCHAR(8) PRIMARY KEY NOT NULL COMMENT '부서코드',
  `GUBUN` VARCHAR(2) COMMENT '구분',
  `KDN_LEADER_ID` VARCHAR(10) COMMENT '팀장사번',
  `KDN_LEADER_NAME` VARCHAR(100) COMMENT '팀장이름',
  `DGLN_TEL_NO` VARCHAR(20) COMMENT '사선전화번호',
  `SSO_ID` VARCHAR(10) COMMENT 'SSOID'
);

CREATE TABLE `its_work_opinion_req` (
  `OPN_ID` VARCHAR(20) NOT NULL COMMENT '의견ID',
  `FRST_REG_DT` DATETIME COMMENT '최초등록일시',
  `FRST_REGR_EMPNO` VARCHAR(10) COMMENT '최초등록사번',
  `LST_CHG_DT` DATETIME COMMENT '최종변경일시',
  `LST_CHGR_EMPNO` VARCHAR(10) COMMENT '최종변경사번',
  `INSTR_NO` VARCHAR(20) COMMENT '지시번호',
  `REQ_ID` VARCHAR(30) COMMENT '청구ID',
  `OPN_CTT` VARCHAR(4000) COMMENT '의견내용',
  PRIMARY KEY (`OPN_ID`)
);

CREATE TABLE `its_work_opinion` (
  `OPN_ID` VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '의견ID',
  `FRST_REG_DT` DATETIME COMMENT '최초등록일시',
  `FRST_REGR_EMPNO` VARCHAR(10) COMMENT '최초등록자사번',
  `LST_CHG_DT` DATETIME COMMENT '최종변경일시',
  `LST_CHGR_EMPNO` VARCHAR(10) COMMENT '최종변경자사번',
  `INSTR_NO` VARCHAR(20) COMMENT '지시번호',
  `REQ_ID` VARCHAR(30) COMMENT '청구ID',
  `WRTR_EMPNO` VARCHAR(10) COMMENT '작성자사번',
  `WRTR_NM` VARCHAR(60) COMMENT '작성자명',
  `OPN_CTT` VARCHAR(4000) COMMENT '의견내용',
  `OPN_YN` VARCHAR(1) COMMENT '의견여부'
);

CREATE TABLE `its_work_opinion_attach` (
  `OPN_ID` VARCHAR(20) NOT NULL COMMENT '의견ID',
  `SEQ_NO` DECIMAL(10,0) NOT NULL COMMENT '시퀀스번호',
  `FRST_REG_DT` DATETIME COMMENT '최초등록일시',
  `FRST_REGR_EMPNO` VARCHAR(10) COMMENT '최초등록자사번',
  `LST_CHG_DT` DATETIME COMMENT '최종변경일시',
  `LST_CHGR_EMPNO` VARCHAR(10) COMMENT '최종변경자사번',
  `RL_FILE_NM` VARCHAR(255) COMMENT '실제파일명',
  `FILE_NM` VARCHAR(100) COMMENT '파일명',
  `FILE_PTH_CTT` VARCHAR(500) COMMENT '파일경로내용',
  `FILE_CPCT` DECIMAL(10,0) COMMENT '파일용량',
  PRIMARY KEY (`OPN_ID`, `SEQ_NO`)
);

CREATE TABLE `its_work_history` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '처리번호',
  `SEQ` VARCHAR(3) NOT NULL COMMENT '순번',
  `REG_SABUN` VARCHAR(8) COMMENT '결재자사번',
  `ACT_ID` VARCHAR(3) COMMENT '작업ID',
  `ACT_ID_NM` VARCHAR(200) COMMENT '작업한글명',
  `ACT_SIGN` VARCHAR(1) COMMENT '유형코드',
  `REG_NAME` VARCHAR(12) COMMENT '결재자이름',
  `REG_DT` VARCHAR(14) COMMENT '결재일',
  `REG_CNTNT` VARCHAR(4000) COMMENT '결재의견',
  PRIMARY KEY (`INST_ID`, `SEQ`)
);

CREATE TABLE `its_work_history_old` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '처리번호',
  `SEQ` VARCHAR(3) NOT NULL COMMENT '순번',
  `REG_SABUN` VARCHAR(10) NOT NULL COMMENT '결재자사번',
  `ACT_ID` VARCHAR(3) COMMENT '작업ID',
  `ACT_ID_NM` VARCHAR(200) COMMENT '작업한글명',
  `ACT_SIGN` VARCHAR(1) COMMENT '유형코드',
  `REG_NAME` VARCHAR(12) COMMENT '결재자이름',
  `REG_DT` VARCHAR(14) COMMENT '결재일',
  `REG_CNTNT` VARCHAR(4000) COMMENT '결재의견',
  PRIMARY KEY (`INST_ID`, `SEQ`, `REG_SABUN`)
);

CREATE TABLE `its_sign_save` (
  `REG_SABUN` VARCHAR(10) PRIMARY KEY NOT NULL COMMENT '현재결재자',
  `SUPER_SABUN` VARCHAR(10) COMMENT '상위결재자'
);

CREATE TABLE `its_n_sign` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '요청/처리번호',
  `SABUN` VARCHAR(10) NOT NULL COMMENT '사번',
  `ACT_ID` VARCHAR(3) COMMENT '진행단계',
  `NAME` VARCHAR(10) COMMENT '이름',
  PRIMARY KEY (`INST_ID`, `SABUN`)
);

CREATE TABLE `its_lock_yn` (
  `USER_ID` VARCHAR(8) PRIMARY KEY NOT NULL COMMENT '사번',
  `FAIL_TIME` VARCHAR(14) COMMENT '접속실패시간'
);

CREATE TABLE `its_n_sla_log` (
  `SLA_INSERT_DT` VARCHAR(14) PRIMARY KEY NOT NULL COMMENT 'SLA연계일',
  `RESULT` VARCHAR(1000) COMMENT 'SLA연계결과'
);

CREATE TABLE `its_chg_log` (
  `LOG_ID` VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '로그ID',
  `FRST_REG_DT` DATE COMMENT '최초등록일시',
  `FRST_REGR_EMPNO` VARCHAR(10) COMMENT '최초등록자사번',
  `LST_CHG_DT` DATE COMMENT '최종변경일시',
  `LST_CHGR_EMPNO` VARCHAR(10) COMMENT '최종변경자사번',
  `INSTR_NO` VARCHAR(20) COMMENT '지시번호',
  `CHG_CTT` VARCHAR(60) COMMENT '변경내용',
  `CLI_ID` VARCHAR(10) COMMENT '구분ID',
  `CFNS_DT` DATE COMMENT '완료일시',
  `CHG_RSN_CTT` VARCHAR(4000) COMMENT '변경사유내용'
);

CREATE TABLE `its_access_log` (
  `SABUN` VARCHAR(10) PRIMARY KEY NOT NULL COMMENT '사번',
  `CONNECT_TIME` DATE COMMENT '접속시간',
  `LOGIN_DT` VARCHAR(8) COMMENT '마지막접속일',
  `CNT` DECIMAL(10,0) COMMENT '로그인시도횟수'
);

CREATE TABLE `its_chg_pwd` (
  `SABUN` VARCHAR(10) PRIMARY KEY NOT NULL COMMENT '사번',
  `UPT_DT` VARCHAR(14) COMMENT '변경일'
);

CREATE TABLE `its_code_20170919` (
  `GUBUN` VARCHAR(2) NOT NULL COMMENT '구분',
  `CODE` VARCHAR(2) NOT NULL COMMENT '코드',
  `BIGO` VARCHAR(100) COMMENT '비고',
  `CODE_NAME` VARCHAR(30) COMMENT '코드이름',
  `UPT_DT` VARCHAR(14) COMMENT '등록일',
  `VIEW_ORDER` DECIMAL(2,0) COMMENT '순번',
  PRIMARY KEY (`GUBUN`, `CODE`)
);

CREATE TABLE `its_code` (
  `GUBUN` VARCHAR(2) NOT NULL COMMENT '구분',
  `CODE` VARCHAR(2) NOT NULL COMMENT '코드',
  `BIGO` VARCHAR(100) COMMENT '비고',
  `CODE_NAME` VARCHAR(30) COMMENT '코드이름',
  `UPT_DT` VARCHAR(14) COMMENT '등록일',
  `VIEW_ORDER` DECIMAL(2,0) COMMENT '순번',
  PRIMARY KEY (`GUBUN`, `CODE`)
);

CREATE TABLE `its_uhd_tonghapcd` (
  `ORI_CD` VARCHAR(4) NOT NULL COMMENT '원통합코드',
  `TONG_CD` VARCHAR(4) NOT NULL COMMENT '통합코드',
  `BIGO` VARCHAR(100) COMMENT '사업소명',
  PRIMARY KEY (`ORI_CD`, `TONG_CD`)
);

CREATE TABLE `its_service_type` (
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  `UPPER_SEQ` CHAR(2) NOT NULL COMMENT '상위순번',
  `SEQ_VALUE` VARCHAR(35) COMMENT '순번내용',
  `REF_NAME` VARCHAR(20) COMMENT '참조명',
  `REF_SEQ` CHAR(2) COMMENT '참조순번',
  PRIMARY KEY (`SEQ`, `UPPER_SEQ`)
);

CREATE TABLE `its_psnlgt_code` (
  `ZCODE` VARCHAR(2) NOT NULL COMMENT 'Z코드',
  `ACODE` VARCHAR(4) NOT NULL COMMENT 'A코드',
  `ZTEXT` VARCHAR(10) COMMENT 'Z코드명',
  `ATEXT` VARCHAR(40) COMMENT 'A코드명',
  PRIMARY KEY (`ZCODE`, `ACODE`)
);

CREATE TABLE `its_wf_act` (
  `ACT_ID` VARCHAR(3) PRIMARY KEY NOT NULL COMMENT '유형코드',
  `ACT_NAME` VARCHAR(100) COMMENT '유형명',
  `UPT_DT` VARCHAR(14) COMMENT '등록일',
  `USE_YN` VARCHAR(1) COMMENT '사용여부'
);

CREATE TABLE `its_stat_saupso` (
  `SEQ` INT PRIMARY KEY NOT NULL COMMENT '순번',
  `SAUPSO` VARCHAR(20) COMMENT '사업소명',
  `OF_CD` VARCHAR(16) COMMENT '코드명'
);

CREATE TABLE `its_service_type_delete` (
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  `UPPER_SEQ` CHAR(2) NOT NULL COMMENT '상위순번',
  `SEQ_VALUE` VARCHAR(35) COMMENT '순번내용',
  `REF_NAME` VARCHAR(20) COMMENT '참조명',
  `REF_SEQ` CHAR(2) COMMENT '참조순번',
  PRIMARY KEY (`SEQ`, `UPPER_SEQ`)
);

CREATE TABLE `its_stat_upmu` (
  `SEQ` INT PRIMARY KEY NOT NULL COMMENT '순번',
  `UPMU` VARCHAR(10) COMMENT '업무코드'
);

CREATE TABLE `its_holiday_info` (
  `HOLIDAY_DATE` VARCHAR(8) PRIMARY KEY NOT NULL COMMENT '공휴일날짜',
  `HOLIDAY_TITLE` VARCHAR(50) COMMENT '공휴일명'
);

CREATE TABLE `its_im_dmail_info_13` (
  `SEQIDX` VARCHAR(100) PRIMARY KEY NOT NULL COMMENT '순번',
  `SUBJECT` VARCHAR(255) COMMENT '제목',
  `SQL` VARCHAR(4000) COMMENT 'SQL',
  `REJECT_SLIST_IDX` VARCHAR(10) COMMENT '인덱스1',
  `BLOCK_GROUP_IDX` VARCHAR(10) COMMENT '인덱스2',
  `MAILFROM` VARCHAR(255) COMMENT '발송자',
  `MAILTO` VARCHAR(255) COMMENT '수신자',
  `REPLYTO` VARCHAR(255) COMMENT '회신자',
  `ERRORSTO` VARCHAR(255) COMMENT '에러회신자',
  `HTML` VARCHAR(10) COMMENT 'HTML코드여부',
  `ENCODING` VARCHAR(10) COMMENT '인코딩여부',
  `CHARSET` VARCHAR(50) COMMENT '캐릭터셋',
  `SDATE` VARCHAR(14) COMMENT '전송일',
  `TDATE` VARCHAR(14) COMMENT '전송종료일',
  `DURATION_SET` VARCHAR(10) COMMENT '설정1',
  `CLICK_SET` VARCHAR(10) COMMENT '설정2',
  `SITE_SET` VARCHAR(10) COMMENT '설정3',
  `ATC_SET` VARCHAR(10) COMMENT '설정4',
  `GUBUN` VARCHAR(24) COMMENT '시스템코드',
  `RNAME` VARCHAR(128) COMMENT '담당자',
  `MTYPE` VARCHAR(10) COMMENT '설정5',
  `U_IDX` VARCHAR(10) COMMENT '설정6',
  `G_IDX` VARCHAR(10) COMMENT '설정7',
  `MSGFLAG` VARCHAR(10) COMMENT '전송구분',
  `CONTENT` VARCHAR(4000) COMMENT '전송내용'
);

CREATE TABLE `its_im_dmail_info_13_backup` (
  `SEQIDX` VARCHAR(100) PRIMARY KEY NOT NULL COMMENT '순번',
  `SUBJECT` VARCHAR(255) COMMENT '제목',
  `SQL` VARCHAR(4000) COMMENT 'SQL',
  `REJECT_SLIST_IDX` VARCHAR(10) COMMENT '인덱스1',
  `BLOCK_GROUP_IDX` VARCHAR(10) COMMENT '인덱스2',
  `MAILFROM` VARCHAR(255) COMMENT '발송자',
  `MAILTO` VARCHAR(255) COMMENT '수신자',
  `REPLYTO` VARCHAR(255) COMMENT '회신자',
  `ERRORSTO` VARCHAR(255) COMMENT '에러회신자',
  `HTML` VARCHAR(10) COMMENT 'HTML코드여부',
  `ENCODING` VARCHAR(10) COMMENT '인코딩여부',
  `CHARSET` VARCHAR(50) COMMENT '캐릭터셋',
  `SDATE` VARCHAR(14) COMMENT '전송일',
  `TDATE` VARCHAR(14) COMMENT '전송종료일',
  `DURATION_SET` VARCHAR(10) COMMENT '설정1',
  `CLICK_SET` VARCHAR(10) COMMENT '설정2',
  `SITE_SET` VARCHAR(10) COMMENT '설정3',
  `ATC_SET` VARCHAR(10) COMMENT '설정4',
  `GUBUN` VARCHAR(24) COMMENT '시스템코드',
  `RNAME` VARCHAR(128) COMMENT '담당자',
  `MTYPE` VARCHAR(10) COMMENT '설정5',
  `U_IDX` VARCHAR(10) COMMENT '설정6',
  `G_IDX` VARCHAR(10) COMMENT '설정7',
  `MSGFLAG` VARCHAR(10) COMMENT '전송구분',
  `CONTENT` VARCHAR(4000) COMMENT '전송내용'
);

CREATE TABLE `its_im_dmail_info_13_kepco` (
  `SEQIDX` VARCHAR(100) PRIMARY KEY NOT NULL COMMENT '순번',
  `SUBJECT` VARCHAR(255) COMMENT '제목',
  `SQL` VARCHAR(4000) COMMENT 'SQL',
  `REJECT_SLIST_IDX` VARCHAR(10) COMMENT '인덱스1',
  `BLOCK_GROUP_IDX` VARCHAR(10) COMMENT '인덱스2',
  `MAILFROM` VARCHAR(255) COMMENT '발송자',
  `MAILTO` VARCHAR(255) COMMENT '수신자',
  `REPLYTO` VARCHAR(255) COMMENT '회신자',
  `ERRORSTO` VARCHAR(255) COMMENT '에러회신자',
  `HTML` VARCHAR(10) COMMENT 'HTML코드여부',
  `ENCODING` VARCHAR(10) COMMENT '인코딩여부',
  `CHARSET` VARCHAR(50) COMMENT '캐릭터셋',
  `SDATE` VARCHAR(14) COMMENT '전송일',
  `TDATE` VARCHAR(14) COMMENT '전송종료일',
  `DURATION_SET` VARCHAR(10) COMMENT '설정1',
  `CLICK_SET` VARCHAR(10) COMMENT '설정2',
  `SITE_SET` VARCHAR(10) COMMENT '설정3',
  `ATC_SET` VARCHAR(10) COMMENT '설정4',
  `GUBUN` VARCHAR(24) COMMENT '시스템코드',
  `RNAME` VARCHAR(128) COMMENT '담당자',
  `MTYPE` VARCHAR(10) COMMENT '설정5',
  `U_IDX` VARCHAR(10) COMMENT '설정6',
  `G_IDX` VARCHAR(10) COMMENT '설정7',
  `MSGFLAG` VARCHAR(10) COMMENT '전송구분',
  `CONTENT` VARCHAR(4000) COMMENT '전송내용'
);

CREATE TABLE `its_im_dmail_info_13_etc` (
  `SEQIDX` VARCHAR(100) PRIMARY KEY NOT NULL COMMENT '순번',
  `SUBJECT` VARCHAR(255) COMMENT '제목',
  `SQL` VARCHAR(4000) COMMENT 'SQL',
  `REJECT_SLIST_IDX` VARCHAR(10) COMMENT '인덱스1',
  `BLOCK_GROUP_IDX` VARCHAR(10) COMMENT '인덱스2',
  `MAILFROM` VARCHAR(255) COMMENT '발송자',
  `MAILTO` VARCHAR(255) COMMENT '수신자',
  `REPLYTO` VARCHAR(255) COMMENT '회신자',
  `ERRORSTO` VARCHAR(255) COMMENT '에러회신자',
  `HTML` VARCHAR(10) COMMENT 'HTML코드여부',
  `ENCODING` VARCHAR(10) COMMENT '인코딩여부',
  `CHARSET` VARCHAR(50) COMMENT '캐릭터셋',
  `SDATE` VARCHAR(14) COMMENT '전송일',
  `TDATE` VARCHAR(14) COMMENT '전송종료일',
  `DURATION_SET` VARCHAR(10) COMMENT '설정1',
  `CLICK_SET` VARCHAR(10) COMMENT '설정2',
  `SITE_SET` VARCHAR(10) COMMENT '설정3',
  `ATC_SET` VARCHAR(10) COMMENT '설정4',
  `GUBUN` VARCHAR(24) COMMENT '시스템코드',
  `RNAME` VARCHAR(128) COMMENT '담당자',
  `MTYPE` VARCHAR(10) COMMENT '설정5',
  `U_IDX` VARCHAR(10) COMMENT '설정6',
  `G_IDX` VARCHAR(10) COMMENT '설정7',
  `MSGFLAG` VARCHAR(10) COMMENT '전송구분',
  `CONTENT` VARCHAR(4000) COMMENT '전송내용'
);

CREATE TABLE `its_em_tran` (
  `TRAN_PR` VARCHAR(10) NOT NULL COMMENT '연번',
  `TRAN_PHONE` VARCHAR(20) NOT NULL COMMENT '수신전화번호',
  `TRAN_CALLBACK` VARCHAR(20) NOT NULL COMMENT '회신전화번호',
  `TRAN_STATUS` VARCHAR(1) COMMENT '전송상태',
  `TRAN_DATE` DATE COMMENT '발송일',
  `TRAN_MSG` VARCHAR(80) COMMENT '메세지내용',
  `TRAN_ETC1` VARCHAR(40) COMMENT '시스템명',
  `TRAN_ETC2` VARCHAR(40) COMMENT '담당자',
  `TRAN_ETC3` VARCHAR(40) COMMENT '시스템코드1',
  `TRAN_ETC4` VARCHAR(40) COMMENT '시스템코드2',
  `INST_ID` VARCHAR(14) COMMENT '문서번호',
  `RCV_NAME` VARCHAR(30) COMMENT '수신자이름',
  `RCV_SABUN` VARCHAR(10) COMMENT '수신자사번',
  `OLD_ACT_ID` VARCHAR(3) COMMENT '현진행단계',
  `NEW_ACT_ID` VARCHAR(3) COMMENT '다음진행단계',
  `NOTICE_TYPE` VARCHAR(3) COMMENT '타입',
  `KEPCO_YN` VARCHAR(1) COMMENT '수신자한전여부',
  `SEND_GB` VARCHAR(1) COMMENT '전송구분',
  PRIMARY KEY (`TRAN_PR`, `TRAN_PHONE`, `TRAN_CALLBACK`)
);

CREATE TABLE `its_em_tran_hist` (
  `TRAN_PR` VARCHAR(10) NOT NULL COMMENT '연번',
  `TRAN_PHONE` VARCHAR(20) NOT NULL COMMENT '수신전화번호',
  `TRAN_CALLBACK` VARCHAR(20) NOT NULL COMMENT '회신전화번호',
  `TRAN_STATUS` VARCHAR(1) COMMENT '전송상태',
  `TRAN_DATE` DATE COMMENT '발송일',
  `TRAN_MSG` VARCHAR(80) COMMENT '메세지내용',
  `TRAN_ETC1` VARCHAR(40) COMMENT '시스템명',
  `TRAN_ETC2` VARCHAR(40) COMMENT '담당자',
  `TRAN_ETC3` VARCHAR(40) COMMENT '시스템코드1',
  `TRAN_ETC4` VARCHAR(40) COMMENT '시스템코드2',
  `INST_ID` VARCHAR(14) COMMENT '문서번호',
  `RCV_NAME` VARCHAR(30) COMMENT '수신자이름',
  `RCV_SABUN` VARCHAR(10) COMMENT '수신자사번',
  `OLD_ACT_ID` VARCHAR(3) COMMENT '현진행단계',
  `NEW_ACT_ID` VARCHAR(3) COMMENT '다음진행단계',
  `NOTICE_TYPE` VARCHAR(3) COMMENT '타입',
  `KEPCO_YN` VARCHAR(1) COMMENT '수신자한전여부',
  `SEND_GB` VARCHAR(1) COMMENT '전송구분',
  PRIMARY KEY (`TRAN_PR`, `TRAN_PHONE`, `TRAN_CALLBACK`)
);

CREATE TABLE `its_sms_auth` (
  `PHONE` VARCHAR(15) NOT NULL COMMENT '전화번호',
  `AUTH_KEY` VARCHAR(6) NOT NULL COMMENT '인증번호',
  `REG_DT` DATE COMMENT '등록일',
  `TYPE` VARCHAR(2) COMMENT '유형',
  `REG_SABUN` VARCHAR(10) COMMENT '등록자사번',
  `TRAN_SABUN` VARCHAR(10) COMMENT '수신인사번',
  `KEY_ID` VARCHAR(10) COMMENT '인증번호고유키',
  `INST_ID` VARCHAR(12) COMMENT '지시서번호',
  `TRAN_PR` VARCHAR(10) COMMENT 'SMS발송인덱스',
  PRIMARY KEY (`PHONE`, `AUTH_KEY`)
);

CREATE TABLE `its_it_work_report_del` (
  `INST_ID` VARCHAR(14) PRIMARY KEY NOT NULL COMMENT '처리번호',
  `REQ_ID` VARCHAR(14) COMMENT '요청번호',
  `CHANGE_TITLE` VARCHAR(1000) COMMENT '지시제목',
  `CHANGE_REASON` VARCHAR(4000) COMMENT '지시내용',
  `SERVICE_TYPE` VARCHAR(2) COMMENT '서비스구분',
  `SYSTEM_CD` VARCHAR(6) COMMENT '시스템코드',
  `WORK_GUBUN` VARCHAR(2) COMMENT '작업구분',
  `EXPT_FP_CNT_EI` DECIMAL(10,0) COMMENT '예상기능_EI',
  `EXPT_FP_CNT_EO` DECIMAL(10,0) COMMENT '예상기능_EO',
  `EXPT_FP_CNT_EQ` DECIMAL(10,0) COMMENT '예상기능_EQ',
  `EXPT_FP_CNT_ILF` DECIMAL(10,0) COMMENT '예상기능_ILF',
  `EXPT_FP_CNT_EIF` DECIMAL(10,0) COMMENT '예상기능_EIF',
  `WORK_TYPE` VARCHAR(2) COMMENT '작업타입',
  `WORK_LEVEL` VARCHAR(2) COMMENT '작업레벨',
  `WORK_PERIOD_MANUAL` VARCHAR(5) COMMENT '작업기간메뉴얼',
  `WORK_PERIOD` VARCHAR(5) COMMENT '작업기간',
  `WORK_CHANGE_PERIOD` VARCHAR(5) COMMENT '변경기간',
  `WORK_CHANGE_PERIOD_CMT` VARCHAR(4000) COMMENT '변경기간_사유',
  `EXPECTED_FINISHED_DT` VARCHAR(14) COMMENT '완료예정일',
  `WORK_CODE` VARCHAR(3) COMMENT '형상연계용작업코드',
  `REQUEST_CODE` VARCHAR(3) COMMENT '형상연계용요청코드',
  `WORK_START_DT` VARCHAR(14) COMMENT '지시시작일',
  `WORK_END_DT` VARCHAR(14) COMMENT '지시종료일',
  `REPORT_DT` VARCHAR(14) COMMENT '작업보고일',
  `IS_SUCCESS` VARCHAR(1) COMMENT '합격여부',
  `SATISFY_POINT` VARCHAR(3) COMMENT '만족도',
  `SATISFY_CNT` VARCHAR(4000) COMMENT '만족도의견',
  `ACT_ID` VARCHAR(3) COMMENT '진행단계',
  `APPROVE1_SABUN` VARCHAR(10) COMMENT '1차결재자사번',
  `APPROVE1_NAME` VARCHAR(12) COMMENT '1차결재자이름',
  `APPROVE1_DT` VARCHAR(14) COMMENT '1차결재일',
  `APPROVE2_SABUN` VARCHAR(10) COMMENT '2차결재자사번',
  `APPROVE2_NAME` VARCHAR(12) COMMENT '2차결재자이름',
  `APPROVE2_DT` VARCHAR(14) COMMENT '2차결재일',
  `APPROVE3_SABUN` VARCHAR(10) COMMENT '3차결재자사번',
  `APPROVE3_NAME` VARCHAR(12) COMMENT '3차결재자이름',
  `APPROVE3_DT` VARCHAR(14) COMMENT '3차결재일',
  `REG_USER_SABUN` VARCHAR(10) COMMENT '등록자사번',
  `REG_USER_NAME` VARCHAR(12) COMMENT '등록자이름',
  `REG_USER_DEP_CD` VARCHAR(16) COMMENT '등록자부서코드',
  `REG_USER_DEP_NM` VARCHAR(500) COMMENT '등록자부서명',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  `WORKER_SABUN` VARCHAR(10) COMMENT '작업자ID',
  `WORKER_NAME` VARCHAR(30) COMMENT '작업자이름',
  `WORKER_DEP_CD` VARCHAR(8) COMMENT '작업부서',
  `WORKER_WORK_CNT` VARCHAR(3) COMMENT '작업자작업건수',
  `WORKER_WORK_DAYS` VARCHAR(5) COMMENT '작업자작업일수',
  `ITMS_INST_ID` VARCHAR(10) COMMENT 'ITMS처리번호',
  `EXPT_FP_SUM` DECIMAL(10,0) COMMENT '예상기능점수합계',
  `CHANGE_ROOT` VARCHAR(2000) COMMENT '변경사유',
  `DEL_DT` VARCHAR(14) COMMENT '삭제일',
  `DEL_SABUN` VARCHAR(10) COMMENT '삭제자사번'
);

CREATE TABLE `its_real_work_report` (
  `INST_ID` VARCHAR(14) PRIMARY KEY NOT NULL COMMENT '요청번호',
  `CHANGE_TITLE` VARCHAR(1000) COMMENT '요청서제목',
  `CHANGE_REASON` VARCHAR(4000) COMMENT '요청서내용',
  `UPMU_TYPE` VARCHAR(3) COMMENT '업무유형_SEQ',
  `UPMU_TYPE_NAME1` VARCHAR(100) COMMENT '업무유형한글명1',
  `UPMU_TYPE_NAME2` VARCHAR(100) COMMENT '업무유형한글명2',
  `SERVICE_TYPE` VARCHAR(2) COMMENT '서비스유형',
  `SERVICE_TYPE_NM` VARCHAR(30) COMMENT '서비스유형한글명',
  `STATUS_CD` VARCHAR(3) COMMENT '현상태코드',
  `STATUS_NM` VARCHAR(20) COMMENT '현상태값',
  `EXPECTED_DT` VARCHAR(14) COMMENT '희망완료일',
  `WORK_START_DT` VARCHAR(14) COMMENT '요청일',
  `WORK_END_DT` VARCHAR(14) COMMENT '종료일',
  `APPROVE1_SABUN` VARCHAR(10) COMMENT '1차결재자사번',
  `APPROVE1_NAME` VARCHAR(12) COMMENT '1차결재자이름',
  `APPROVE1_DT` VARCHAR(14) COMMENT '1차결재일',
  `APPROVE2_SABUN` VARCHAR(10) COMMENT '2차결재자사번',
  `APPROVE2_NAME` VARCHAR(12) COMMENT '2차결재자이름',
  `APPROVE2_DT` VARCHAR(14) COMMENT '2차결재일',
  `APPROVE3_SABUN` VARCHAR(10) COMMENT '3차결재자사번',
  `APPROVE3_NAME` VARCHAR(12) COMMENT '3차결재자이름',
  `APPROVE3_DT` VARCHAR(14) COMMENT '3차결재일',
  `SEND_IT_SABUN` VARCHAR(10) COMMENT '수신자사번',
  `SEND_IT_NAME` VARCHAR(12) COMMENT '수신자이름',
  `WORK_SABUN` VARCHAR(10) COMMENT '작업자사번',
  `WORK_NAME` VARCHAR(12) COMMENT '작업자이름',
  `REG_USER_SABUN` VARCHAR(10) COMMENT '등록자사번',
  `REG_USER_NAME` VARCHAR(12) COMMENT '등록자이름',
  `REG_USER_DEP_CD` VARCHAR(16) COMMENT '등록자소속코드',
  `REG_USER_DEP_NM` VARCHAR(500) COMMENT '등록자소속명',
  `SATISFY_POINT` VARCHAR(3) COMMENT '만족도점수',
  `SATISFY_CNT` VARCHAR(4000) COMMENT '만족도내용',
  `SMSFLG` VARCHAR(1) COMMENT 'SMS수신여부',
  `SYSTEM_CD` VARCHAR(6) COMMENT '시스템코드',
  `TESTFLAG` VARCHAR(2) COMMENT '요청자테스트참여여부',
  `TEST_MODE_YN` VARCHAR(1) COMMENT '테스트여부',
  `CHG_RSN_CTT` VARCHAR(4000) COMMENT '변경사유내용',
  `OPPB_YN` VARCHAR(1) COMMENT '공개여부'
);

CREATE TABLE `its_it_work_report` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '처리번호',
  `REQ_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  `CHANGE_TITLE` VARCHAR(1000) COMMENT '지시제목',
  `CHANGE_REASON` VARCHAR(4000) COMMENT '지시내용',
  `SERVICE_TYPE` VARCHAR(2) COMMENT '서비스유형',
  `SYSTEM_CD` VARCHAR(6) COMMENT '시스템코드',
  `WORK_GUBUN` VARCHAR(2) COMMENT '작업구분',
  `EXPT_FP_CNT_EI` DECIMAL(10,0) COMMENT '예상기능_EI',
  `EXPT_FP_CNT_EO` DECIMAL(10,0) COMMENT '예상기능_EO',
  `EXPT_FP_CNT_EQ` DECIMAL(10,0) COMMENT '예상기능_EQ',
  `EXPT_FP_CNT_ILF` DECIMAL(10,0) COMMENT '예상기능_ILF',
  `EXPT_FP_CNT_EIF` DECIMAL(10,0) COMMENT '예상기능_EIF',
  `WORK_TYPE` VARCHAR(2) COMMENT '작업유형',
  `WORK_LEVEL` VARCHAR(2) COMMENT '작업레벨',
  `WORK_PERIOD_MANUAL` VARCHAR(5) COMMENT '작업기간메뉴얼',
  `WORK_PERIOD` VARCHAR(5) COMMENT '작업기간',
  `WORK_CHANGE_PERIOD` VARCHAR(5) COMMENT '변경기간',
  `WORK_CHANGE_PERIOD_CMT` VARCHAR(4000) COMMENT '변경기간_사유',
  `EXPECTED_FINISHED_DT` VARCHAR(14) COMMENT '완료예정일',
  `WORK_CODE` VARCHAR(3) COMMENT '형상연계용작업코드',
  `REQUEST_CODE` VARCHAR(3) COMMENT '형상연계용요청코드',
  `WORK_START_DT` VARCHAR(14) COMMENT '지시서시작일',
  `WORK_END_DT` VARCHAR(14) COMMENT '지시서종료일',
  `REPORT_DT` VARCHAR(14) COMMENT '작업보고일',
  `IS_SUCCESS` VARCHAR(1) COMMENT '합격여부',
  `SATISFY_POINT` VARCHAR(3) COMMENT '만족도',
  `SATISFY_CNT` VARCHAR(4000) COMMENT '만족도의견',
  `ACT_ID` VARCHAR(3) COMMENT '진행단계',
  `APPROVE1_SABUN` VARCHAR(10) COMMENT '1차결재자사번',
  `APPROVE1_NAME` VARCHAR(12) COMMENT '1차결재자이름',
  `APPROVE1_DT` VARCHAR(14) COMMENT '1차결재일',
  `APPROVE2_SABUN` VARCHAR(10) COMMENT '2차결재자사번',
  `APPROVE2_NAME` VARCHAR(12) COMMENT '2차결재자이름',
  `APPROVE2_DT` VARCHAR(14) COMMENT '2차결재일',
  `APPROVE3_SABUN` VARCHAR(10) COMMENT '3차결재자사번',
  `APPROVE3_NAME` VARCHAR(12) COMMENT '3차결재자이름',
  `APPROVE3_DT` VARCHAR(14) COMMENT '3차결재일',
  `REG_USER_SABUN` VARCHAR(10) COMMENT '등록자사번',
  `REG_USER_NAME` VARCHAR(12) COMMENT '등록자이름',
  `REG_USER_DEP_CD` VARCHAR(16) COMMENT '등록자부서코드',
  `REG_USER_DEP_NM` VARCHAR(500) COMMENT '등록자부서명',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  `WORKER_SABUN` VARCHAR(10) COMMENT '작업자ID',
  `WORKER_NAME` VARCHAR(30) COMMENT '작업자이름',
  `WORKER_DEP_CD` VARCHAR(8) COMMENT '작업부서',
  `WORKER_WORK_CNT` VARCHAR(3) COMMENT '작업자작업건수',
  `WORKER_WORK_DAYS` VARCHAR(5) COMMENT '작업자작업일수',
  `ITMS_INST_ID` VARCHAR(10) COMMENT 'ITMS처리번호',
  `EXPT_FP_SUM` DECIMAL(10,0) COMMENT '예상기능점수합계',
  `CHANGE_ROOT` VARCHAR(2000) COMMENT '변경사유',
  `TEST_MODE_YN` VARCHAR(1) COMMENT '테스트모드여부',
  `USER_MANUAL_YN` VARCHAR(1) COMMENT '사용자메뉴얼갱신여부',
  `DEPLOY_DT` VARCHAR(14) COMMENT '배포일',
  `OPPB_YN` VARCHAR(1) COMMENT '공개여부',
  `DRS_IMPT_YN` VARCHAR(1) COMMENT '재해복구시스템영향여부',
  PRIMARY KEY (`INST_ID`, `REQ_ID`)
);

CREATE TABLE `smeta_work_report` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '지시번호',
  `REQ_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  `REQ_ID2` VARCHAR(14) NOT NULL COMMENT '요청번호',
  PRIMARY KEY (`INST_ID`, `REQ_ID`, `REQ_ID2`)
);

CREATE TABLE `its_user_info_secret` (
  `INST_ID` DECIMAL(10,0) NOT NULL COMMENT '지시번호',
  `DOC_TYPE` VARCHAR(1) NOT NULL COMMENT '문서타입',
  `REQ_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  `IS_SECRET` VARCHAR(1) COMMENT '개인정보포함여부',
  `USER_SECRET_CONTENT` VARCHAR(4000) COMMENT '개인정보내용',
  `ATTACH_EXPIRE_DATE` CHAR(8) COMMENT '파기일',
  `OPPB_CL_YN` VARCHAR(1) COMMENT '공개구분여부',
  PRIMARY KEY (`INST_ID`, `DOC_TYPE`, `REQ_ID`)
);

CREATE TABLE `its_work_result` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '처리번호',
  `REQ_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  `RESULT` VARCHAR(4000) COMMENT '작업결과',
  `WORKER_ID` VARCHAR(8) COMMENT '작업자ID',
  `WORKER_NAME` VARCHAR(12) COMMENT '작업자이름',
  `WORKER_DEP_NM` VARCHAR(1000) COMMENT '작업자부서명',
  `WORKER_TEL` VARCHAR(20) COMMENT '작업자전화',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  `QRY_CTT` VARCHAR(4000) COMMENT '쿼리내용',
  PRIMARY KEY (`INST_ID`, `REQ_ID`)
);

CREATE TABLE `smeta_work_result` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '지시번호',
  `REQUEST_ID` VARCHAR(12) NOT NULL COMMENT '요청아이디',
  `REQUEST_ITEM_ID` VARCHAR(12) NOT NULL COMMENT '요청항목아이디',
  `INST_ID2` VARCHAR(14) NOT NULL COMMENT '처리번호',
  `REQ_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  PRIMARY KEY (`INST_ID`, `REQUEST_ID`, `REQUEST_ITEM_ID`, `REQ_ID`)
);

CREATE TABLE `its_work_result_attach` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '처리번호',
  `SEQ` VARCHAR(3) NOT NULL COMMENT '순번',
  `REQ_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  `REAL_FILE_NAME` VARCHAR(1000) COMMENT '실제파일명',
  `FILE_NAME` VARCHAR(1000) COMMENT '변환파일명',
  `FILE_LOCATION` VARCHAR(1000) COMMENT '파일위치',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  `ITMSFLG` CHAR(1) COMMENT 'ITMS구분값',
  `ATTACH_TYPE` VARCHAR(2) COMMENT '첨부파일유형',
  `FILE_SIZE` VARCHAR(10) COMMENT '파일크기',
  PRIMARY KEY (`INST_ID`, `SEQ`, `REQ_ID`)
);

CREATE TABLE `its_work_result_fp` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '지시번호',
  `SEQ` VARCHAR(3) NOT NULL COMMENT '순번',
  `REQ_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  `GUBUN` VARCHAR(1) COMMENT '구분',
  `TYPE` VARCHAR(3) COMMENT '기능유형',
  `FP` DECIMAL(2,1) COMMENT '기능점수',
  `FP_NAME` VARCHAR(200) COMMENT '기능명',
  `UPT_SABUN` VARCHAR(10) COMMENT '처리자사번',
  `UPT_DT` VARCHAR(14) COMMENT '처리날짜',
  `LANG_TP_NM` VARCHAR(100) COMMENT '언어유형명',
  PRIMARY KEY (`INST_ID`, `SEQ`, `REQ_ID`)
);

CREATE TABLE `its_real_work_report_attach` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  `SEQ` VARCHAR(3) NOT NULL COMMENT '순번',
  `REAL_FILE_NAME` VARCHAR(1000) COMMENT '실제파일명',
  `FILE_NAME` VARCHAR(1000) COMMENT '변환파일명',
  `FILE_LOCATION` VARCHAR(1000) COMMENT '파일위치',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  `DEL_FLAG` VARCHAR(2) COMMENT '삭제여부',
  `FILE_SIZE` VARCHAR(10) COMMENT '파일크기',
  PRIMARY KEY (`INST_ID`, `SEQ`)
);

CREATE TABLE `its_rcll_log` (
  `RCLL_CL_SEQNO` VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '회수구분순번',
  `FRST_REGR_DT` DATE COMMENT '최초등록일시',
  `FRST_REGR_EMPNO` VARCHAR(10) COMMENT '최초등록자사번',
  `LST_CHG_DT` DATE COMMENT '최종변경일시',
  `LST_CHGR_EMPNO` VARCHAR(10) COMMENT '최종변경자사번',
  `REQ_ID` VARCHAR(30) COMMENT '청구ID',
  `INSTR_NO` VARCHAR(20) COMMENT '지시번호',
  `RCLL_RSN_CTT` VARCHAR(4000) COMMENT '회수사유내용'
);

CREATE TABLE `its_notice_attach` (
  `NOTICE_NO` VARCHAR(14) NOT NULL COMMENT '문서번호',
  `SEQ` VARCHAR(3) NOT NULL COMMENT '순번',
  `REAL_FILE_NAME` VARCHAR(1000) COMMENT '실제파일명',
  `FILE_NAME` VARCHAR(1000) COMMENT '변환파일명',
  `FILE_LOCATION` VARCHAR(1000) COMMENT '실서버위치',
  `REG_DT` VARCHAR(14) COMMENT '날짜',
  `TYPE` VARCHAR(1) COMMENT '종류',
  `FILE_SIZE` VARCHAR(10) COMMENT '파일크기',
  PRIMARY KEY (`NOTICE_NO`, `SEQ`)
);

CREATE TABLE `its_it_work_report_attach` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '처리번호',
  `SEQ` VARCHAR(3) NOT NULL COMMENT '순번',
  `REAL_FILE_NAME` VARCHAR(1000) COMMENT '실제파일명',
  `FILE_NAME` VARCHAR(1000) COMMENT '변환파일명',
  `FILE_LOCATION` VARCHAR(1000) COMMENT '파일위치',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  `ATTACH_TYPE` VARCHAR(2) COMMENT '첨부파일유형',
  `FILE_SIZE` VARCHAR(10) COMMENT '파일크기',
  PRIMARY KEY (`INST_ID`, `SEQ`)
);

CREATE TABLE `its_it_receiver` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '문서번호',
  `SABUN` VARCHAR(10) NOT NULL COMMENT '사번',
  `DEP_ID` VARCHAR(10) COMMENT '부서코드',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  PRIMARY KEY (`INST_ID`, `SABUN`)
);

CREATE TABLE `its_receive` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '지시서번호',
  `SABUN` VARCHAR(10) NOT NULL COMMENT '사번',
  `NAME` VARCHAR(10) COMMENT '이름',
  PRIMARY KEY (`INST_ID`, `SABUN`)
);

CREATE TABLE `its_notice_attach_bak` (
  `NOTICE_NO` DECIMAL(4,0) NOT NULL COMMENT '문서번호',
  `SEQ` VARCHAR(3) NOT NULL COMMENT '순번',
  `REAL_FILE_NAME` VARCHAR(1000) COMMENT '실제파일명',
  `FILE_NAME` VARCHAR(1000) COMMENT '변환파일명',
  `FILE_LOCATION` VARCHAR(1000) COMMENT '실서버위치',
  `REG_DT` VARCHAR(14) COMMENT '날짜',
  `FILE_SIZE` VARCHAR(10) COMMENT '종류',
  PRIMARY KEY (`NOTICE_NO`, `SEQ`)
);

CREATE TABLE `its_real_work_report_old` (
  `INST_ID` VARCHAR(14) PRIMARY KEY NOT NULL COMMENT '요청번호',
  `CHANGE_TITLE` VARCHAR(1000) COMMENT '요청서제목',
  `CHANGE_REASON` VARCHAR(4000) COMMENT '요청서내용',
  `UPMU_TYPE` VARCHAR(3) COMMENT '업무유형_SEQ',
  `UPMU_TYPE_NAME1` VARCHAR(100) COMMENT '업무유형한글명1',
  `UPMU_TYPE_NAME2` VARCHAR(100) COMMENT '업무유형한글명2',
  `SERVICE_TYPE` VARCHAR(2) COMMENT '서비스유형',
  `SERVICE_TYPE_NM` VARCHAR(30) COMMENT '서비스유형한글명',
  `STATUS_CD` VARCHAR(3) COMMENT '현상태코드',
  `STATUS_NM` VARCHAR(20) COMMENT '현상태값',
  `EXPECTED_DT` VARCHAR(14) COMMENT '희망완료일',
  `WORK_START_DT` VARCHAR(14) COMMENT '요청일',
  `WORK_END_DT` VARCHAR(14) COMMENT '종료일',
  `APPROVE1_SABUN` VARCHAR(10) COMMENT '1차결재자사번',
  `APPROVE1_NAME` VARCHAR(12) COMMENT '1차결재자이름',
  `APPROVE1_DT` VARCHAR(14) COMMENT '1차결재일',
  `APPROVE2_SABUN` VARCHAR(10) COMMENT '2차결재자사번',
  `APPROVE2_NAME` VARCHAR(12) COMMENT '2차결재자이름',
  `APPROVE2_DT` VARCHAR(14) COMMENT '2차결재일',
  `APPROVE3_SABUN` VARCHAR(10) COMMENT '3차결재자사번',
  `APPROVE3_NAME` VARCHAR(12) COMMENT '3차결재자이름',
  `APPROVE3_DT` VARCHAR(14) COMMENT '3차결재일',
  `SEND_IT_SABUN` VARCHAR(10) COMMENT '수신자사번',
  `SEND_IT_NAME` VARCHAR(12) COMMENT '수신자이름',
  `WORK_SABUN` VARCHAR(10) COMMENT '작업자사번',
  `WORK_NAME` VARCHAR(12) COMMENT '작업자이름',
  `REG_USER_SABUN` VARCHAR(10) COMMENT '등록자사번',
  `REG_USER_NAME` VARCHAR(12) COMMENT '등록자이름',
  `REG_USER_DEP_CD` VARCHAR(16) COMMENT '등록자소속코드',
  `REG_USER_DEP_NM` VARCHAR(500) COMMENT '등록자소속명',
  `SATISFY_POINT` VARCHAR(3) COMMENT '만족도점수',
  `SATISFY_CNT` VARCHAR(4000) COMMENT '만족도내용',
  `SMSFLG` VARCHAR(1) COMMENT 'SMS수신여부',
  `SYSTEM_CD` VARCHAR(6) COMMENT '시스템코드',
  `TESTFLAG` VARCHAR(2) COMMENT '요청자테스트참여여부',
  `TEST_MODE_YN` VARCHAR(1) COMMENT '테스트여부',
  `OPPB_YN` VARCHAR(1) COMMENT '공개여부'
);

CREATE TABLE `its_notice` (
  `NOTICE_NO` DECIMAL(6,0) PRIMARY KEY NOT NULL COMMENT '문서번호',
  `NOTICE_TITLE` VARCHAR(1000) COMMENT '제목',
  `NOTICE_DEP_CD` VARCHAR(16) COMMENT '부서코드',
  `NOTICE_CONTENTS` VARCHAR(4000) COMMENT '내용',
  `PRIORITY` DECIMAL(2,0) COMMENT '정렬',
  `REG_USER_SABUN` VARCHAR(10) COMMENT '등록자사번',
  `REG_USER_DEP_CD` VARCHAR(16) COMMENT '등록자부서코드',
  `REG_USER_NAME` VARCHAR(12) COMMENT '등록자이름',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  `END_DT` VARCHAR(14) COMMENT '게시종료일',
  `DEL_YN` VARCHAR(1) COMMENT '삭제여부',
  `VIEW_CNT` DECIMAL(3,0) COMMENT '조회수',
  `TYPE` VARCHAR(1) COMMENT '자료실공지사항구분'
);

CREATE TABLE `its_it_work_report_old` (
  `INST_ID` VARCHAR(14) NOT NULL COMMENT '처리번호',
  `REQ_ID` VARCHAR(14) NOT NULL COMMENT '요청번호',
  `CHANGE_TITLE` VARCHAR(1000) COMMENT '지시제목',
  `CHANGE_REASON` VARCHAR(4000) COMMENT '지시내용',
  `SERVICE_TYPE` VARCHAR(2) COMMENT '서비스유형',
  `SYSTEM_CD` VARCHAR(6) COMMENT '시스템코드',
  `WORK_GUBUN` VARCHAR(2) COMMENT '작업구분',
  `EXPT_FP_CNT_EI` DECIMAL(10,0) COMMENT '예상기능_EI',
  `EXPT_FP_CNT_EO` DECIMAL(10,0) COMMENT '예상기능_EO',
  `EXPT_FP_CNT_EQ` DECIMAL(10,0) COMMENT '예상기능_EQ',
  `EXPT_FP_CNT_ILF` DECIMAL(10,0) COMMENT '예상기능_ILF',
  `EXPT_FP_CNT_EIF` DECIMAL(10,0) COMMENT '예상기능_EIF',
  `WORK_TYPE` VARCHAR(2) COMMENT '작업유형',
  `WORK_LEVEL` VARCHAR(2) COMMENT '작업레벨',
  `WORK_PERIOD_MANUAL` VARCHAR(5) COMMENT '작업기간메뉴얼',
  `WORK_PERIOD` VARCHAR(5) COMMENT '작업기간',
  `WORK_CHANGE_PERIOD` VARCHAR(5) COMMENT '변경기간',
  `WORK_CHANGE_PERIOD_CMT` VARCHAR(4000) COMMENT '변경기간_사유',
  `EXPECTED_FINISHED_DT` VARCHAR(14) COMMENT '완료예정일',
  `WORK_CODE` VARCHAR(3) COMMENT '형상연계용작업코드',
  `REQUEST_CODE` VARCHAR(3) COMMENT '형상연계용요청코드',
  `WORK_START_DT` VARCHAR(14) COMMENT '지시서시작일',
  `WORK_END_DT` VARCHAR(14) COMMENT '지시서종료일',
  `REPORT_DT` VARCHAR(14) COMMENT '작업보고일',
  `IS_SUCCESS` VARCHAR(1) COMMENT '합격여부',
  `SATISFY_POINT` VARCHAR(3) COMMENT '만족도',
  `SATISFY_CNT` VARCHAR(4000) COMMENT '만족도의견',
  `ACT_ID` VARCHAR(3) COMMENT '진행단계',
  `APPROVE1_SABUN` VARCHAR(10) COMMENT '1차결재자사번',
  `APPROVE1_NAME` VARCHAR(12) COMMENT '1차결재자이름',
  `APPROVE1_DT` VARCHAR(14) COMMENT '1차결재일',
  `APPROVE2_SABUN` VARCHAR(10) COMMENT '2차결재자사번',
  `APPROVE2_NAME` VARCHAR(12) COMMENT '2차결재자이름',
  `APPROVE2_DT` VARCHAR(14) COMMENT '2차결재일',
  `APPROVE3_SABUN` VARCHAR(10) COMMENT '3차결재자사번',
  `APPROVE3_NAME` VARCHAR(12) COMMENT '3차결재자이름',
  `APPROVE3_DT` VARCHAR(14) COMMENT '3차결재일',
  `REG_USER_SABUN` VARCHAR(10) COMMENT '등록자사번',
  `REG_USER_NAME` VARCHAR(12) COMMENT '등록자이름',
  `REG_USER_DEP_CD` VARCHAR(16) COMMENT '등록자부서코드',
  `REG_USER_DEP_NM` VARCHAR(500) COMMENT '등록자부서명',
  `REG_DT` VARCHAR(14) COMMENT '등록일',
  `WORKER_SABUN` VARCHAR(10) COMMENT '작업자ID',
  `WORKER_NAME` VARCHAR(30) COMMENT '작업자이름',
  `WORKER_DEP_CD` VARCHAR(8) COMMENT '작업부서',
  `WORKER_WORK_CNT` VARCHAR(3) COMMENT '작업자작업건수',
  `WORKER_WORK_DAYS` VARCHAR(5) COMMENT '작업자작업일수',
  `ITMS_INST_ID` VARCHAR(10) COMMENT 'ITMS처리번호',
  `EXPT_FP_SUM` DECIMAL(10,0) COMMENT '예상기능점수합계',
  `CHANGE_ROOT` VARCHAR(2000) COMMENT '변경사유',
  `TEST_MODE_YN` VARCHAR(1) COMMENT '테스트모드여부',
  `USER_MANUAL_YN` VARCHAR(1) COMMENT '사용자메뉴얼갱신여부',
  `DEPLOY_DT` VARCHAR(14) COMMENT '배포일',
  `OPPB_YN` VARCHAR(1) COMMENT '공개여부',
  PRIMARY KEY (`INST_ID`, `REQ_ID`)
);

CREATE TABLE `its_system_info_delete` (
  `DOMAIN` CHAR(2) NOT NULL COMMENT '대분류',
  `SUBDOMAIN` CHAR(2) NOT NULL COMMENT '중분류',
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  `SYSTEM_CD` CHAR(6) COMMENT '시스템코드',
  `CMS_NAME` VARCHAR(100) COMMENT '단위시스템명',
  `SYSTEM_CONTENTS` VARCHAR(2000) COMMENT '개요',
  `MAINTAIN_YN` CHAR(1) COMMENT '유지구분',
  `DAILY_YN` CHAR(1) COMMENT '일상구분',
  `BRANCH_DAILY_YN` CHAR(1) COMMENT '사업소일상구분',
  `FP` DECIMAL(6,2) COMMENT '기능점수',
  `START_DATE` VARCHAR(14) COMMENT '위탁개시일',
  `CLOSE_DATE` VARCHAR(14) COMMENT '위탁해지일',
  `INPUT_DATE` VARCHAR(14) COMMENT '입력일',
  `UPDATE_DATE` VARCHAR(14) COMMENT '수정일',
  `DOMAIN_NAME` VARCHAR(20) COMMENT '도메인명_대분류',
  `SUBDOMAIN_NAME` VARCHAR(20) COMMENT '서브도메인명_중분류',
  `SUB_NAME` VARCHAR(150) COMMENT '하위도메인명',
  `SAP_YN` VARCHAR(1) COMMENT 'ERP여부',
  `ITMS_BIZ_CD` VARCHAR(4) COMMENT '형상관리연계코드',
  `NEW_ITMS_YN` VARCHAR(1) COMMENT '형상관리관리여부',
  `DEPLOY_START_DT` VARCHAR(14) COMMENT '배포시작일',
  PRIMARY KEY (`DOMAIN`, `SUBDOMAIN`, `SEQ`)
);

CREATE TABLE `its_system_info` (
  `DOMAIN` CHAR(2) NOT NULL COMMENT '대분류',
  `SUBDOMAIN` CHAR(2) NOT NULL COMMENT '중분류',
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  `SYSTEM_CD` CHAR(6) COMMENT '시스템코드',
  `CMS_NAME` VARCHAR(100) COMMENT '단위시스템명',
  `SYSTEM_CONTENTS` VARCHAR(2000) COMMENT '개요',
  `MAINTAIN_YN` CHAR(1) COMMENT '유지구분',
  `DAILY_YN` CHAR(1) COMMENT '일상구분',
  `BRANCH_DAILY_YN` CHAR(1) COMMENT '사업소일상구분',
  `FP` DECIMAL(6,2) COMMENT '기능점수',
  `START_DATE` VARCHAR(14) COMMENT '위탁개시일',
  `CLOSE_DATE` VARCHAR(14) COMMENT '위탁해지일',
  `INPUT_DATE` VARCHAR(14) COMMENT '입력일',
  `UPDATE_DATE` VARCHAR(14) COMMENT '수정일',
  `DOMAIN_NAME` VARCHAR(20) COMMENT '도메인명',
  `SUBDOMAIN_NAME` VARCHAR(35) COMMENT '서브도메인명',
  `SUB_NAME` VARCHAR(150) COMMENT '하위도메인명',
  `SAP_YN` VARCHAR(1) COMMENT 'ERP여부',
  `ITMS_BIZ_CD` VARCHAR(4) COMMENT '형상관리연계코드',
  `NEW_ITMS_YN` VARCHAR(1) COMMENT '형상관리관리여부',
  `DEPLOY_START_DT` VARCHAR(14) COMMENT '배포시작일',
  `EP_SYS_YN` VARCHAR(1) COMMENT 'EP시스템여부',
  `EP_GRP_NM` VARCHAR(50) COMMENT 'EP그룹명',
  `DRS_IMPT_YN` VARCHAR(1) COMMENT '재해복구시스템영향여부',
  PRIMARY KEY (`DOMAIN`, `SUBDOMAIN`, `SEQ`)
);

CREATE TABLE `its_importance` (
  `SYSTEM_CD` CHAR(6) PRIMARY KEY NOT NULL COMMENT '시스템코드',
  `EFFECT_RANGE_SCORE` DECIMAL(10,0) COMMENT '영향도범위점수',
  `DATA_IMPORTANCE_SCORE` DECIMAL(10,0) COMMENT '데이터중요도점수',
  `USER_COUNT_SCORE` DECIMAL(10,0) COMMENT '이용자수점수',
  `EFFECT_RANGE_EST` VARCHAR(20) COMMENT '영향도범위평가',
  `DATA_IMPORTANCE_EST` VARCHAR(20) COMMENT '데이터중요도평가',
  `USER_COUNT_EST` VARCHAR(20) COMMENT '이용자수평가',
  `CONNECT_COUNT` DECIMAL(12,0) COMMENT '접속자수',
  `USER_COUNT` DECIMAL(12,0) COMMENT '사용자수',
  `LINK_COUNT` DECIMAL(3,0) COMMENT '연계건수',
  `DATA_COUNT` DECIMAL(15,0) COMMENT '주요테이블건수',
  `EMERGENCY_DEGREE` CHAR(1) COMMENT '긴급도',
  `EX_IN` CHAR(1) COMMENT '내외부구분'
);

CREATE TABLE `its_server_info` (
  `SYSTEM_CD` CHAR(6) NOT NULL COMMENT '시스템코드',
  `SEQ` VARCHAR(2) NOT NULL COMMENT '순번',
  `HOSTNAME` VARCHAR(10) COMMENT '호스트명',
  `USED` VARCHAR(200) COMMENT '용도',
  PRIMARY KEY (`SYSTEM_CD`, `SEQ`)
);

CREATE TABLE `its_meta_system` (
  `DOMAIN` CHAR(2) NOT NULL COMMENT '대분류',
  `SUBDOMAIN` CHAR(2) NOT NULL COMMENT '중분류',
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  PRIMARY KEY (`DOMAIN`, `SUBDOMAIN`, `SEQ`)
);

CREATE TABLE `its_system_fp` (
  `SYSTEM_CD` CHAR(6) NOT NULL COMMENT '시스템코드',
  `YYMM` CHAR(6) NOT NULL COMMENT '년월',
  `MAINTAIN_FP` DECIMAL(5,0) COMMENT '유지보수_기능점수',
  `HEAD_DAILY_FP` DECIMAL(5,0) COMMENT '본사_일상운영_기능점수',
  `BRANCH_DAILY_FP` DECIMAL(5,0) COMMENT '지사_일상운영_기능점수',
  `BIGO` VARCHAR(60) COMMENT '비고',
  PRIMARY KEY (`SYSTEM_CD`, `YYMM`)
);

CREATE TABLE `its_system_sub_info` (
  `SYSTEM_CD` CHAR(6) NOT NULL COMMENT '시스템코드',
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  `SUB_NAME` VARCHAR(150) COMMENT '단위시스템SUB명',
  PRIMARY KEY (`SYSTEM_CD`, `SEQ`)
);

CREATE TABLE `its_system_sub_info_delete` (
  `SYSTEM_CD` CHAR(6) NOT NULL COMMENT '시스템코드',
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  `SUB_NAME` VARCHAR(150) COMMENT '단위시스템SUB명',
  PRIMARY KEY (`SYSTEM_CD`, `SEQ`)
);

CREATE TABLE `its_scrt_tchgr` (
  `TCHGR_EMPNO` VARCHAR(10) PRIMARY KEY NOT NULL COMMENT '담당자사번',
  `FRST_REG_DT` DATETIME COMMENT '최초등록일시',
  `FRST_REGR_EMPNO` VARCHAR(10) COMMENT '최초등록자사번',
  `LST_CHG_DT` DATETIME COMMENT '최종변경일시',
  `LST_CHGR_EMPNO` VARCHAR(10) COMMENT '최종변경자사번',
  `TCHGR_NM` VARCHAR(60) COMMENT '담당자명',
  `USE_YN` VARCHAR(1) COMMENT '사용여부'
);

CREATE TABLE `its_basic_cal_info` (
  `MEASURE_DEVISION` CHAR(2) PRIMARY KEY NOT NULL COMMENT '측정구분',
  `MEASURE_SPECIFIC` VARCHAR(200) COMMENT '측정기준명',
  `MEASURE_RATE` DECIMAL(3,0) COMMENT '비중',
  `MEASURE_ITEM` VARCHAR(100) COMMENT '측정항목',
  `MEASURE_HIGH` DECIMAL(3,0) COMMENT '측정_상',
  `MEASURE_MEDIUM` DECIMAL(3,0) COMMENT '측정_중',
  `MEASURE_LOW` DECIMAL(3,0) COMMENT '측정_하',
  `MEASURE_CAL` VARCHAR(200) COMMENT '산정계산식',
  `MEASURE_TYPE` VARCHAR(10) COMMENT '유형',
  `NUMBEROFDAY` DECIMAL(2,1) COMMENT '표준일수'
);

CREATE TABLE `its_language_info` (
  `SYSTEM_CD` CHAR(6) PRIMARY KEY NOT NULL COMMENT '시스템코드',
  `DEV_LAN1` VARCHAR(20) COMMENT '언어1',
  `DEV_LAN2` VARCHAR(20) COMMENT '언어2',
  `DEV_LAN3` VARCHAR(20) COMMENT '언어3',
  `DEV_LAN4` VARCHAR(20) COMMENT '언어4',
  `DEV_LAN5` VARCHAR(20) COMMENT '언어5',
  `BIGO` VARCHAR(60) COMMENT '비고'
);

CREATE TABLE `its_admin_auth` (
  `EMPNO` VARCHAR(10) PRIMARY KEY NOT NULL COMMENT '사번',
  `FRST_REG_DT` DATETIME COMMENT '최초등록일시',
  `FRST_REGR_EMPNO` VARCHAR(10) COMMENT '최초등록자사번',
  `LST_CHG_DT` DATETIME COMMENT '최종변경일시',
  `LST_CHGR_EMPNO` VARCHAR(10) COMMENT '최종변경자사번',
  `EMP_NM` VARCHAR(60) COMMENT '사원명',
  `UPD_AUTH_YN` VARCHAR(1) COMMENT '수정권한여부',
  `MNG_AUTH_YN` VARCHAR(1) COMMENT '관리권한여부',
  `REG_AUTH_YN` VARCHAR(1) COMMENT '등록권한여부'
);

CREATE TABLE `its_self_map` (
  `SYSTEM_CD` VARCHAR(6) PRIMARY KEY NOT NULL COMMENT '시스템코드',
  `KEPCO_SABUN1` VARCHAR(10) COMMENT '한전1차사번',
  `KEPCO_NAME1` VARCHAR(10) COMMENT '한전1차이름',
  `KEPCO_SABUN2` VARCHAR(10) COMMENT '한전2차사번',
  `KEPCO_NAME2` VARCHAR(10) COMMENT '한전2차이름'
);

CREATE TABLE `its_saupso_map` (
  `SAUPSO_CD` VARCHAR(4) PRIMARY KEY NOT NULL COMMENT '사업소코드',
  `KEPCO_DEP_NAME` VARCHAR(30) COMMENT '한전담당자부서명',
  `KEPCO_SABUN` VARCHAR(10) COMMENT '한전담당자사번',
  `KEPCO_NAME` VARCHAR(10) COMMENT '한전담당자이름',
  `KDN_DEP_ID` VARCHAR(8) COMMENT 'KDN담당자부서코드',
  `KDN_SABUN` VARCHAR(10) COMMENT 'KDN담당자사번',
  `KDN_NAME` VARCHAR(10) COMMENT 'KDN담당자이름'
);

CREATE TABLE `its_saupso_worker_map` (
  `SYSTEM_CD` VARCHAR(4) NOT NULL COMMENT '시스템코드',
  `SOSOK_CD` VARCHAR(4) NOT NULL COMMENT '소속코드',
  `KDN_DEP_CD` VARCHAR(8) COMMENT 'KDN담당자부서코드',
  `KDN_SABUN` VARCHAR(10) COMMENT 'KDN담당자사번',
  `KDN_NM` VARCHAR(10) COMMENT 'KDN담당자이름',
  `KDN_TEL` VARCHAR(20) COMMENT 'KDN담당자전화번호',
  PRIMARY KEY (`SYSTEM_CD`, `SOSOK_CD`)
);

CREATE TABLE `its_person_info` (
  `SYSTEM_CD` VARCHAR(6) NOT NULL COMMENT '시스템코드',
  `COMPANY_GB` VARCHAR(2) NOT NULL COMMENT '회사구분',
  `SABUN` VARCHAR(10) NOT NULL COMMENT '사번',
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  `NAME` VARCHAR(20) COMMENT '이름',
  `TEL` VARCHAR(13) COMMENT '전화',
  `DEPT_NAME` VARCHAR(40) COMMENT '관리부서',
  `ETC` VARCHAR(60) COMMENT '비고',
  PRIMARY KEY (`SYSTEM_CD`, `COMPANY_GB`, `SABUN`, `SEQ`)
);

CREATE TABLE `smeta_person_info` (
  `SYSTEM_CD` VARCHAR(30) NOT NULL COMMENT '시스템ID',
  `SABUN` VARCHAR(10) NOT NULL COMMENT '담당자사번',
  `COMPANY_GB` VARCHAR(2) NOT NULL COMMENT '회사구분',
  PRIMARY KEY (`SYSTEM_CD`, `SABUN`, `COMPANY_GB`)
);

CREATE TABLE `its_person_info_delete` (
  `SYSTEM_CD` CHAR(6) NOT NULL COMMENT '시스템코드',
  `COMPANY_GB` CHAR(2) NOT NULL COMMENT '회사구분',
  `SABUN` VARCHAR(10) NOT NULL COMMENT '사번',
  `SEQ` CHAR(2) NOT NULL COMMENT '순번',
  `NAME` VARCHAR(20) COMMENT '이름',
  `TEL` VARCHAR(12) COMMENT '전화',
  `DEPT_NAME` VARCHAR(40) COMMENT '관리부서',
  `ETC` VARCHAR(60) COMMENT '비고',
  PRIMARY KEY (`SYSTEM_CD`, `COMPANY_GB`, `SABUN`, `SEQ`)
);

ALTER TABLE `its_kdn_user` COMMENT = 'KDN직원정보';

ALTER TABLE `its_kdn_dep` COMMENT = 'KDN부서';

ALTER TABLE `smeta_user` COMMENT = 'SMETA 사용자';

ALTER TABLE `its_kepco_login` COMMENT = 'KDN로그인';

ALTER TABLE `its_kdn_dep_map` COMMENT = 'KDN수신부서팀장';

ALTER TABLE `its_work_opinion_req` COMMENT = '의견요청 내역';

ALTER TABLE `its_work_opinion` COMMENT = '의견요청';

ALTER TABLE `its_work_opinion_attach` COMMENT = '의견요청 첨부파일';

ALTER TABLE `its_work_history` COMMENT = '결재이력';

ALTER TABLE `its_work_history_old` COMMENT = '과거문서_결재이력';

ALTER TABLE `its_sign_save` COMMENT = '결재라인자동설정';

ALTER TABLE `its_n_sign` COMMENT = '현재결재자정보';

ALTER TABLE `its_lock_yn` COMMENT = '로그인실패';

ALTER TABLE `its_n_sla_log` COMMENT = 'SLA 연계확인';

ALTER TABLE `its_chg_log` COMMENT = '기한변경 로그';

ALTER TABLE `its_access_log` COMMENT = '접속로그';

ALTER TABLE `its_chg_pwd` COMMENT = '최근패스워드 변경 관리';

ALTER TABLE `its_code_20170919` COMMENT = '코드정보_2017';

ALTER TABLE `its_code` COMMENT = '코드 정보';

ALTER TABLE `its_uhd_tonghapcd` COMMENT = 'UHD통합코드';

ALTER TABLE `its_service_type` COMMENT = '업무분야별코드';

ALTER TABLE `its_psnlgt_code` COMMENT = '근태정보코드';

ALTER TABLE `its_wf_act` COMMENT = '작업유형코드';

ALTER TABLE `its_stat_saupso` COMMENT = '사업소코드설정';

ALTER TABLE `its_service_type_delete` COMMENT = '업무분야별코드_삭제정보';

ALTER TABLE `its_stat_upmu` COMMENT = '업무코드설정';

ALTER TABLE `its_holiday_info` COMMENT = '영업일관련휴일정보';

ALTER TABLE `its_im_dmail_info_13` COMMENT = '이메일발송정보';

ALTER TABLE `its_im_dmail_info_13_backup` COMMENT = '이메일발송정보_이력';

ALTER TABLE `its_im_dmail_info_13_kepco` COMMENT = '이메일발송정보_한전이력';

ALTER TABLE `its_im_dmail_info_13_etc` COMMENT = '이메일발송정보_기타이력';

ALTER TABLE `its_em_tran` COMMENT = '서비스종합SMS발송';

ALTER TABLE `its_em_tran_hist` COMMENT = '서비스종합SMS발송이력';

ALTER TABLE `its_sms_auth` COMMENT = 'SMS인증';

ALTER TABLE `its_it_work_report_del` COMMENT = '지시서_IT부서_삭제';

ALTER TABLE `its_real_work_report` COMMENT = '요청서_실무부서';

ALTER TABLE `its_it_work_report` COMMENT = '지시서_IT부서';

ALTER TABLE `smeta_work_report` COMMENT = 'SMETA 작업지시서';

ALTER TABLE `its_user_info_secret` COMMENT = '개인정보포함여부';

ALTER TABLE `its_work_result` COMMENT = '결과보고_KDN';

ALTER TABLE `smeta_work_result` COMMENT = 'SMETA작업결과';

ALTER TABLE `its_work_result_attach` COMMENT = '결과보고_KDN첨부';

ALTER TABLE `its_work_result_fp` COMMENT = '유지보수후결과';

ALTER TABLE `its_real_work_report_attach` COMMENT = '요청서_실무부서_첨부';

ALTER TABLE `its_rcll_log` COMMENT = '요청서회수관리';

ALTER TABLE `its_notice_attach` COMMENT = '자료실/공지사항첨부파일';

ALTER TABLE `its_it_work_report_attach` COMMENT = '지시서_IT부서_첨부';

ALTER TABLE `its_it_receiver` COMMENT = 'IT부서_접수자';

ALTER TABLE `its_receive` COMMENT = 'IT부서수신자';

ALTER TABLE `its_notice_attach_bak` COMMENT = '공지사항 첨부';

ALTER TABLE `its_real_work_report_old` COMMENT = '과거요청서_실무부서';

ALTER TABLE `its_notice` COMMENT = '자료실/공지사항';

ALTER TABLE `its_it_work_report_old` COMMENT = '과거지시서_IT부서';

ALTER TABLE `its_system_info_delete` COMMENT = '정보시스템삭제정보';

ALTER TABLE `its_system_info` COMMENT = '정보시스템정보';

ALTER TABLE `its_importance` COMMENT = '정보시스템별중요도정보';

ALTER TABLE `its_server_info` COMMENT = '서버정보';

ALTER TABLE `its_meta_system` COMMENT = 'SMETA시스템';

ALTER TABLE `its_system_fp` COMMENT = '정보시스템별FP';

ALTER TABLE `its_system_sub_info` COMMENT = '정보시스템서브정보';

ALTER TABLE `its_system_sub_info_delete` COMMENT = '정보시스템서브삭제정보';

ALTER TABLE `its_scrt_tchgr` COMMENT = '보안담당자';

ALTER TABLE `its_basic_cal_info` COMMENT = '산출일수기준정보';

ALTER TABLE `its_language_info` COMMENT = '시스템언어정보';

ALTER TABLE `its_admin_auth` COMMENT = '관리자권한';

ALTER TABLE `its_self_map` COMMENT = '자체처리시스템';

ALTER TABLE `its_saupso_map` COMMENT = '지역본부별담당자정보';

ALTER TABLE `its_saupso_worker_map` COMMENT = 'KDN지사별담당자';

ALTER TABLE `its_person_info` COMMENT = '정보시스템별담당자';

ALTER TABLE `smeta_person_info` COMMENT = 'SMETA담당자';

ALTER TABLE `its_person_info_delete` COMMENT = '정보시스템별담당자_이력';

ALTER TABLE `its_kdn_user` ADD FOREIGN KEY (`DEP_ID`) REFERENCES `smeta_user` (`DEP_ID`);

ALTER TABLE `smeta_user` ADD FOREIGN KEY (`LOGIN_ID`) REFERENCES `its_kdn_user` (`LOGIN_ID`);

ALTER TABLE `smeta_user` ADD FOREIGN KEY (`DEP_ID`) REFERENCES `its_kdn_dep` (`DEP_ID`);

ALTER TABLE `its_work_opinion_req` ADD FOREIGN KEY (`OPN_ID`) REFERENCES `its_work_opinion` (`OPN_ID`);

ALTER TABLE `its_work_opinion_attach` ADD FOREIGN KEY (`OPN_ID`) REFERENCES `its_work_opinion` (`OPN_ID`);

ALTER TABLE `its_user_info_secret` ADD FOREIGN KEY (`INST_ID`) REFERENCES `its_real_work_report` (`INST_ID`);

ALTER TABLE `its_it_work_report` ADD FOREIGN KEY (`REQ_ID`) REFERENCES `its_real_work_report` (`INST_ID`);

ALTER TABLE `its_user_info_secret` ADD FOREIGN KEY (`INST_ID`) REFERENCES `its_work_result` (`INST_ID`);

ALTER TABLE `its_it_work_report` ADD FOREIGN KEY (`INST_ID`) REFERENCES `its_work_result` (`INST_ID`);

ALTER TABLE `its_work_result_attach` ADD FOREIGN KEY (`INST_ID`) REFERENCES `its_work_result` (`INST_ID`);

ALTER TABLE `its_work_result_fp` ADD FOREIGN KEY (`INST_ID`) REFERENCES `its_work_result` (`INST_ID`);

ALTER TABLE `smeta_work_result` ADD FOREIGN KEY (`INST_ID`) REFERENCES `its_work_result` (`INST_ID`);

ALTER TABLE `its_user_info_secret` ADD FOREIGN KEY (`INST_ID`) REFERENCES `its_it_work_report` (`INST_ID`);

ALTER TABLE `smeta_person_info` ADD FOREIGN KEY (`SYSTEM_CD`) REFERENCES `its_person_info` (`SYSTEM_CD`);

ALTER TABLE `smeta_person_info` ADD FOREIGN KEY (`COMPANY_GB`) REFERENCES `its_person_info` (`COMPANY_GB`);

ALTER TABLE `smeta_person_info` ADD FOREIGN KEY (`SABUN`) REFERENCES `its_person_info` (`SABUN`);

ALTER TABLE `its_meta_system` ADD FOREIGN KEY (`DOMAIN`) REFERENCES `its_system_info` (`DOMAIN`);

ALTER TABLE `its_meta_system` ADD FOREIGN KEY (`SUBDOMAIN`) REFERENCES `its_system_info` (`SUBDOMAIN`);

ALTER TABLE `its_meta_system` ADD FOREIGN KEY (`SEQ`) REFERENCES `its_system_info` (`SEQ`);

ALTER TABLE `smeta_work_report` ADD FOREIGN KEY (`INST_ID`) REFERENCES `its_it_work_report` (`INST_ID`);

ALTER TABLE `its_im_dmail_info_13_kepco` ADD FOREIGN KEY (`TDATE`) REFERENCES `its_im_dmail_info_13_kepco` (`MSGFLAG`);
